// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPS6z1pEwyfexdsdoY7zUkI5rvXdxKxPM',
    appId: '1:706120420509:web:c3f505f56eb554a2529874',
    messagingSenderId: '706120420509',
    projectId: 'ascend-app-db-2026',
    authDomain: 'ascend-app-db-2026.firebaseapp.com',
    storageBucket: 'ascend-app-db-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsxlTffbwM50qBMSvE9IO3cedkbkA6Lt0',
    appId: '1:706120420509:android:00dbcc9978a26767529874',
    messagingSenderId: '706120420509',
    projectId: 'ascend-app-db-2026',
    storageBucket: 'ascend-app-db-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv8a_a5fm0CQKgH7lCD7GGDcL4YZTBk94',
    appId: '1:706120420509:ios:62fc4066bbe9c5f8529874',
    messagingSenderId: '706120420509',
    projectId: 'ascend-app-db-2026',
    storageBucket: 'ascend-app-db-2026.firebasestorage.app',
    iosBundleId: 'com.example.ascend.ascendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv8a_a5fm0CQKgH7lCD7GGDcL4YZTBk94',
    appId: '1:706120420509:ios:62fc4066bbe9c5f8529874',
    messagingSenderId: '706120420509',
    projectId: 'ascend-app-db-2026',
    storageBucket: 'ascend-app-db-2026.firebasestorage.app',
    iosBundleId: 'com.example.ascend.ascendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPS6z1pEwyfexdsdoY7zUkI5rvXdxKxPM',
    appId: '1:706120420509:web:7d90441722882858529874',
    messagingSenderId: '706120420509',
    projectId: 'ascend-app-db-2026',
    authDomain: 'ascend-app-db-2026.firebaseapp.com',
    storageBucket: 'ascend-app-db-2026.firebasestorage.app',
  );

}